@host = http://localhost:8080

### Registration
POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json
{
	"email": "ivan@test.com",
	"username": "ivanbaci",
	"password": "1234"
}

### Login
POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json
{
	"username": "ivanbaci",
	"password": "1234"
}


### Update category monotributista
PUT {{host}}/user/5ded569595e492394b6cbd1d/category
{
	"category": "MONOTRIBUTISTA"
}

### Update category rel dep
PUT {{host}}/user/5ded569595e492394b6cbd1d/category
{
	"category": "REL_DEPENDENCIA"
}


### Update fiscal data
PUT {{host}}/user/5ded569595e492394b6cbd1d/fiscal-data
{
	"fiscalData": {
		"name": "Ivan",
		"lastName": "Bacigaluppo",
		"cuit": "20396448697"
	}
}

### Monotributista data service provision
POST {{host}}/monotributista/5ded569595e492394b6cbd1d
{
	"activity": "SERVICE_PROVISION",
    "location": {
      "province": "Buenos Aires",
      "city": "La Plata"
    },
    "earnings": 138128,
    "hasShop": false,
    "shopDetails": {
      "quantity": 0,
      "area": 0,
      "paysRental": false,
      "rentalValue": 0,
      "consumedEnergy": 0
    }
}

### Monotributista data products sale
POST {{host}}/monotributista/5ded569595e492394b6cbd1d
{
	"activity": "PRODUCTS_SALE",
    "location": {
      "province": "Buenos Aires",
      "city": "La Plata"
    },
    "earnings": 138128,
    "hasShop": false,
    "shopDetails": {
      "quantity": 0,
      "area": 0,
      "paysRental": false,
      "rentalValue": 0,
      "consumedEnergy": 0
    }
}

### Monotributista get tax situation
GET {{host}}/monotributista/5ded569595e492394b6cbd1d/tax-situation

### Monotributista get category limits
GET {{host}}/monotributista/5ded569595e492394b6cbd1d/category-limits

### Monotributista get taxes
GET {{host}}/monotributista/5ded569595e492394b6cbd1d/tax

### Monotributista bill
POST {{host}}/monotributista/5ded569595e492394b6cbd1d/bill
{
	"date": "20/10/2019",
	"value": 300,
	"title": "servicio",
	"description": "nada"
}

### Get all bills
GET {{host}}/monotributista/5ded569595e492394b6cbd1d/bill?year=2019

### Post rel dep info
POST {{host}}/rel-dep/5ded569595e492394b6cbd1d
{
	"salary": 3000000,
	"isMarried": true,
	"sonsQuantity": 2,
	"paysRental": true,
	"rentalValue": 7000
}

### Save receipt 
POST {{host}}/rel-dep/5ded569595e492394b6cbd1d/receipt
{
	"date": "20/10/2019",
	"value": 30000
}

### Get receipts
GET {{host}}/rel-dep/5ded569595e492394b6cbd1d/receipt?year=2019

### Get rel dep taxes
GET {{host}}/rel-dep/5ded569595e492394b6cbd1d/tax
